
target 'MusicMind' do
  use_frameworks!

  pod 'Firebase/Core', '~> 3.16.0'
  pod 'Firebase/Auth', '~> 3.16.0'
  pod 'Firebase/Storage', '~> 3.16.0'
  pod 'Firebase/Database', '~> 3.16.0'
  pod 'Alamofire'
  #  pod 'SinchVerification-Swift'
  pod 'RecordButton', :git => 'https://github.com/felipericieri/RecordButton.git'
  
end
